[package]
name = "opencl-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencl3 = "0.9.3"
kdtree = "0.7.0"
rayon = "1.7.0"
half = "2.3.1"
indicatif = "0.17.6"
lazy_static = "1.4.0"